kind: Service
apiVersion: v1
metadata:
  name: svc-deploy-loadbalancer-demoapp
  namespace: ns-demo
spec:
  type: LoadBalancer
  selector:
    app: deploy-mydemoapp
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  #loadBalancerIP: 1.2.3.4
