apiVersion: v1
kind: Pod
metadata:
  name: pod-secret-nginx-ssl
  labels:
    app: secret-nginx-ssl
  namespace: ns-mynginx
spec:
  nodeName: ubuntu22-server02
  restartPolicy: OnFailure
  containers:
  - name: nginx
    image: strrzj/my-nginx:v1.1
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: nginx-cret
      mountPath: /etc/nginx/certs
      readOnly: true
    - name: nginx-conf
      mountPath: /etc/nginx/conf.d
      readOnly: true
  volumes: 
  - name: nginx-cret
    secret:
      secretName: secret-nginx-certs
  - name: nginx-conf
    configMap: 
      name: cm-nginx-ssl
      optional: false
