apiVersion: v1
kind: Service
metadata:
  labels:
    app: wordpress
  name: wordpress
spec:
  type: NodePort
  ports:
  - name: http 
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: wordpress
