apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: elastic-system
spec:
  version: 8.11.3
  count: 1
  elasticsearchRef:
    name: "myes"
  http:
    tls:
      selfSignedCertificate:
        disabled: true
    service:
      spec:
        type: LoadBalancer
---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: kibana
#  namespace: elastic-system
#spec:
#  ingressClassName: nginx
#  rules:
#  - host: kibana.magedu.com
#    http:
#      paths:
#      - backend:
#          service:
#            name: kibana-kb-http
#            port:
#              number: 5601
#        path: /
#        pathType: Prefix
#  # tls:
#  # - hosts:
#  #   - host-name
#  #   secretName: tls-secret-name
