apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mydemoapp
  name: mydemoapp
  namespace: ns-demo
spec:
  replicas: 4
  selector:
    matchLabels:
      app: mydemoapp
  template:
    metadata:
      labels:
        app: mydemoapp
    spec:
      containers:
      - image: strrzj/mydemoapp:v1.0
        name: mydemoapp
