apiVersion: v1
kind: Namespace
metadata:
  name: ns-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mydemoapp
  name: mydemoapp
  namespace: ns-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mydemoapp
  template:
    metadata:
      labels:
        app: mydemoapp
    spec:
      containers:
      - image: strrzj/mydemoapp:v1.0
        name: mydemoapp
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mydemoapp
  name: mydemoapp
  namespace: ns-demo
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  externalIPs:
  - 192.168.198.150 
  selector:
    app: mydemoapp
  type: NodePort
status:
  loadBalancer: {}
