apiVersion: v1
kind: Pod
metadata:
  name: startup-post-test
  namespace: default
spec:
  containers:
  - name: post-test
    image: nginx
    lifecycle:
      postStart:
        exec:
          command: ["/bin/sh", "-c", "mkdir -p  /app;echo test > /app/test"]
    startupProbe:
      exec:
        command:  ["/bin/sh","-c","cat /app/test2"]  ## 返回不是0，那就是探测失败
      initialDelaySeconds: 20 ## 指定的这个秒以后才执行探测
      periodSeconds: 5  ## 每隔几秒来运行这个
      timeoutSeconds: 5  ##探测超时，到了超时时间探测还没返回结果说明失败
      successThreshold: 1 ## 成功阈值，连续几次成才算成功
      failureThreshold: 3 ## 失败阈值，连续几次失败才算真失败

