apiVersion: v1
kind: Service
metadata:
  name: svc-server02-mynginx-ssl
  namespace: ns-mynginx
spec:
  type: NodePort
  selector:
    app: secret-nginx-server02-ssl
  ports: 
  - name: 443-443
    port: 443
    protocol: TCP
    targetPort: 443
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  externalIPs:
  - 192.168.198.150
