apiVersion: v1
kind: Pod
metadata:
  name: pod-redis-pvc-nfs-dynamic
  labels:
    app: pvc-nfs-dynamic-redis-pod
  namespace: ns-myredis
spec:
  nodeName: ubuntu22-server03
  containers:
  - name: ubuntu22-server-myredis
    image: redis:6
    ports:
    - name: redisport
      containerPort: 6379
    securityContext:
      privileged: true
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        memory: "64Mi"
        cpu: "200m"
      limits:
        memory: "64Mi"
        cpu: "200m"
    volumeMounts:
    - name: redis-data
      mountPath: /data
  volumes:
  - name: redis-data
    persistentVolumeClaim:
      claimName: pvc-nfs-dynamic-redis
  restartPolicy: OnFailure
