apiVersion: v1
kind: Service
metadata:
  labels:
    app: pvc-nfs-dynamic-redis-pod
  name: svc-demoredis-pvc-nfs-dynamic
  namespace: ns-myredis
spec:
  ports:
  - name: myredisport
    port: 6379
    protocol: TCP
    targetPort: 6379
  externalIPs:
  - 192.168.198.150
  selector:
    app: pvc-nfs-dynamic-redis-pod
  type: NodePort
status:
  loadBalancer: {}
