apiVersion: v1
kind: Service
metadata:
  name: svc-mysql-testdb
  namespace: ns-mysql
spec:
  type: NodePort
  selector:
    app: testdb
  ports: 
  - name: 3306-3306
    port: 3306
    protocol: TCP
    targetPort: 3306
  externalIPs:
  - 192.168.198.150
