apiVersion: v1
kind: Pod
metadata:
  name: mynginx-pod
  labels:
    app: mynginx-pod
  namespace: ns-mynginx
spec:
  containers:
  - name: ubuntu22-server-mynginx
    image: strrzj/my-nginx:v1.1
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        memory: "64Mi"
        cpu: "1"
      limits:
        memory: "64Mi"
        cpu: "1"
    volumeMounts:
    - name: nginx-config
      mountPath: /etc/nginx/conf.d
  volumes:
  - name: nginx-config
    configMap:
      name: mynginx-configmap
  restartPolicy: Never
