apiVersion: v1
kind: Service
metadata:
  labels:
    app: pvc-nfs-dynamic-pod
  name: svc-demonginx-pvc-nfs-dynamic
  namespace: ns-mynginx
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  - name: 81-81
    port: 81
    protocol: TCP
    targetPort: 81
  externalIPs:
  - 192.168.198.150
  selector:
    app: pvc-nfs-dynamic-pod
  type: NodePort
status:
  loadBalancer: {}
