apiVersion: batch/v1
kind: Job
metadata:
  name: job-para-demo
  namespace: ns-demo  
spec:
  template:
    spec:
      containers:
      - name: myjob
        image: strrzj/admin-box:v1.2
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c", "sleep 10"]
      restartPolicy: Never
  completions: 7
  parallelism: 2
  ttlSecondsAfterFinished: 3600
  backoffLimit: 3
  activeDeadlineSeconds: 1200
