apiVersion: v1
kind: Namespace
metadata:
  name: ns-mynginx
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-nginx-pvc
  labels:
    app: pvc-pod
  namespace: ns-mynginx
spec:
  nodeName: ubuntu22-server02
  containers:
  - name: ubuntu22-server-mynginx
    image: strrzj/ubuntu22-server-mynginx:latest
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        memory: "64Mi"
        cpu: "200m"
      limits:
        memory: "64Mi"
        cpu: "200m"
    volumeMounts:
    - name: nginx-data
      mountPath: /etc/nginx/conf.d
      readOnly: true
  volumes:
  - name: nginx-data
    persistentVolumeClaim: 
      claimName: pvc-nginx-nfs
  restartPolicy: OnFailure
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pvc-pod
  name: demonginx-nfs-pvc
  namespace: ns-mynginx
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  - name: 81-81
    port: 81
    protocol: TCP
    targetPort: 81
  externalIPs:
  - 192.168.198.150
  selector:
    app: pvc-pod
  type: NodePort
status:
  loadBalancer: {}
