apiVersion: v1
kind: Namespace
metadata: 
  name: ns-mynginx
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: pvc-nginx-nfs
  namespace: ns-mynginx  
spec: 
  accessModes: ["ReadWriteMany"]
  volumeMode: Filesystem
  resources: 
    requests: 
      storage: 1Gi
    limits: 
      storage: 5Gi
